### PR TITLE
(enh) Build for Linux on ARM.

### PR DESCRIPTION
**Pull request by glennj**
cc does not have a `-m64` option on ARM

### CODE REVIEW

**Comment by glennj** [comment]
There's no github workflow for arm. Here's proof:

```none
$ uname -a
Linux exercism-vm 5.15.0-113-generic #123-Ubuntu SMP Mon Jun 10 08:16:46 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

$ python3 util/test.py
(bin/wrenc) Passed: 96 Failed: 0 Skipped: 4 Path

  ✅ should normalize
  ✅ detect root
  ✅ navigate paths
  ✅ join
  ✅ dirname
  ✅ split
  ✅ windows

Tests:  💯 ✓ 7 passed, 7 total

Runtime

  ✅ have class level constants
  ✅ have details
  ✅ assertVersion
  ✅ have capabilities
  ✅ allow querying capabilities

Tests:  💯 ✓ 5 passed, 5 total

All 99 tests passed (275 expectations).
Skipped 3 tests: 
Skipped 1 tests: Windows
```

**Comment by joshgoebel** [comment]
Does GitHub have a builder for this architecture?

**Comment by glennj** [comment]
Not for free, it looks like:

> In addition to the standard GitHub-hosted runners, GitHub offers customers on GitHub Team and GitHub Enterprise Cloud plans a range of managed virtual machines with advanced features - for example, more cores and disk space, GPU-powered machines, and ARM-powered machines.

https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job

**Comment by joshgoebel** [comment]
So this is all just to remove `-m64`... does Make have anyway to just detect the architecture or add a conditional so the single makefile would work on any Linux?

**Comment by glennj** [comment]
@joshgoebel got it. Now only adds the `-m64` option on x86_64 machines.

**Review by joshgoebel — APPROVED** [review]

**Pull request merged**
